USE yatrik;

-- Default User
INSERT INTO users (user_id, name, display_name, email, password_hash)
VALUES ('YT-2026', 'Tanzeemul Haq', 'Tanzee', 'Tanzemul033@gmail.com', '$2b$10$X3qYk5v9Z1234567890123456789012345678901234567890');

-- 23 Destinations
INSERT INTO destinations (name, state, region, description, image_url, best_time, recommended_days, daily_budget_estimate, travel_notes, latitude, longitude) VALUES
('Lucknow', 'UP', 'North', 'City of Nawabs, known for its rich culture and Awadhi cuisine.', 'NULL', 'October to March', 3, 2500, 'Rich in heritage', 26.8467, 80.9462),
('Jaipur', 'Rajasthan', 'North West', 'The Pink City, famous for its palaces and forts.', 'NULL', 'October to March', 4, 3000, 'Explore the forts', 26.9124, 75.7873),
('Nainital', 'Uttarakhand', 'North', 'Lake district of India, perfect for a peaceful getaway.', 'NULL', 'March to June', 3, 2500, 'Hill station', 29.3919, 79.4542),
('Mussoorie', 'Uttarakhand', 'North', 'Queen of the Hills, offering majestic views of the Himalayas.', 'NULL', 'September to June', 3, 2500, 'Beautiful views', 30.4598, 78.0644),
('Delhi', 'Delhi NCR', 'North', 'Capital city blending historical monuments with modernity.', 'NULL', 'October to March', 4, 3500, 'Busy and historical', 28.6139, 77.2090),
('Kerala (Kochi & Munnar)', 'Kerala', 'South', 'God''s Own Country, famous for its backwaters and tea gardens.', 'NULL', 'September to March', 5, 3000, 'Tropical and lush', 10.8505, 76.2711),
('Goa', 'Goa', 'West', 'Famous for its pristine beaches and vibrant nightlife.', 'NULL', 'November to February', 4, 3500, 'Beach destination', 15.2993, 74.1240),
('Agra', 'UP', 'North', 'Home to the iconic Taj Mahal.', 'NULL', 'October to March', 2, 2000, 'Historical', 27.1767, 78.0081),
('Varanasi', 'UP', 'North', 'The spiritual capital of India, situated on the banks of the Ganges.', 'NULL', 'October to March', 3, 2000, 'Spiritual', 25.3176, 83.0039),
('Rishikesh', 'Uttarakhand', 'North', 'Yoga capital of the world and adventure hub.', 'NULL', 'September to June', 3, 2000, 'Yoga and rafting', 30.0869, 78.2676),
('Manali', 'HP', 'North', 'A high-altitude Himalayan resort town.', 'NULL', 'October to June', 4, 3000, 'Snow peaks', 32.2396, 77.1887),
('Shimla', 'HP', 'North', 'The summer capital of British India, offering colonial charm.', 'NULL', 'March to June', 3, 2500, 'Colonial architecture', 31.1048, 77.1734),
('Amritsar', 'Punjab', 'North', 'Home to the spectacular Golden Temple.', 'NULL', 'November to March', 2, 2000, 'Spiritual and food', 31.6340, 74.8723),
('Udaipur', 'Rajasthan', 'North West', 'The City of Lakes, known for its lavish royal residences.', 'NULL', 'September to March', 3, 3000, 'Romantic city', 24.5854, 73.7125),
('Mumbai', 'Maharashtra', 'West', 'The city of dreams, India''s financial and entertainment capital.', 'NULL', 'October to February', 4, 4000, 'Fast-paced metropolis', 19.0760, 72.8777),
('Bengaluru', 'Karnataka', 'South', 'The Silicon Valley of India, known for its parks and nightlife.', 'NULL', 'September to February', 3, 3500, 'Tech city', 12.9716, 77.5946),
('Hyderabad', 'Telangana', 'South', 'The City of Pearls, famous for its historic sites and biryani.', 'NULL', 'October to March', 3, 2500, 'Historical and culinary', 17.3850, 78.4867),
('Chennai', 'Tamil Nadu', 'South', 'A major cultural and economic center in South India.', 'NULL', 'November to February', 3, 2500, 'Cultural hub', 13.0827, 80.2707),
('Kolkata', 'West Bengal', 'East', 'The cultural capital of India, known for its colonial architecture.', 'NULL', 'October to March', 3, 2500, 'Art and literature', 22.5726, 88.3639),
('Darjeeling', 'West Bengal', 'East', 'Renowned for its tea industry and panoramic views of Kangchenjunga.', 'NULL', 'April to June', 3, 2500, 'Tea gardens', 27.0360, 88.2627),
('Ooty', 'Tamil Nadu', 'South', 'A popular hill station located in the Nilgiri Hills.', 'NULL', 'March to June', 3, 2500, 'Scenic mountains', 11.4064, 76.6932),
('Mysuru', 'Karnataka', 'South', 'Known for its heritage structures and palaces, including the Mysore Palace.', 'NULL', 'October to March', 2, 2000, 'Palaces and silk', 12.2958, 76.6394),
('Andaman & Nicobar', 'Islands', 'Islands', 'A stunning archipelago offering beautiful beaches and water sports.', 'NULL', 'October to May', 5, 5000, 'Tropical paradise', 11.7401, 92.6586);


-- Attractions
INSERT INTO attractions (destination_id, name, category, duration, entry_fee, location) VALUES
(1, 'Bara Imambara', 'Heritage', '2 hours', 50, 'Lucknow'),
(1, 'Chota Imambara', 'Heritage', '1 hour', 25, 'Lucknow'),
(1, 'Rumi Darwaza', 'Heritage', '30 min', 0, 'Lucknow'),
(1, 'British Residency', 'Heritage', '1.5 hours', 25, 'Lucknow'),
(1, 'Hazratganj Market', 'Market', '2 hours', 0, 'Lucknow'),
(2, 'Hawa Mahal', 'Heritage', '1 hour', 50, 'Jaipur'),
(2, 'Amber Fort', 'Heritage', '3 hours', 200, 'Jaipur'),
(2, 'City Palace', 'Heritage', '2 hours', 500, 'Jaipur'),
(2, 'Jantar Mantar', 'Heritage', '1 hour', 50, 'Jaipur'),
(2, 'Nahargarh Fort', 'Heritage', '2 hours', 50, 'Jaipur'),
(3, 'Naini Lake', 'Nature', '2 hours', 150, 'Nainital'),
(3, 'Snow View Point', 'Nature', '1 hour', 0, 'Nainital'),
(3, 'Naina Devi Temple', 'Religious', '1 hour', 0, 'Nainital'),
(3, 'Mall Road', 'Market', '2 hours', 0, 'Nainital'),
(4, 'Kempty Falls', 'Nature', '2 hours', 50, 'Mussoorie'),
(4, 'Gun Hill Point', 'Nature', '1 hour', 100, 'Mussoorie'),
(4, 'Camel''s Back Road', 'Nature', '2 hours', 0, 'Mussoorie'),
(4, 'Lal Tibba', 'Nature', '1 hour', 50, 'Mussoorie'),
(5, 'Red Fort', 'Heritage', '2 hours', 35, 'Delhi'),
(5, 'Qutub Minar', 'Heritage', '1.5 hours', 35, 'Delhi'),
(5, 'India Gate', 'Monument', '1 hour', 0, 'Delhi'),
(5, 'Lotus Temple', 'Religious', '1 hour', 0, 'Delhi'),
(5, 'Humayun''s Tomb', 'Heritage', '1.5 hours', 35, 'Delhi'),
(6, 'Fort Kochi', 'Heritage', '2 hours', 0, 'Kochi'),
(6, 'Mattancherry Palace', 'Heritage', '1 hour', 5, 'Kochi'),
(6, 'Tea Gardens', 'Nature', '3 hours', 0, 'Munnar'),
(6, 'Eravikulam National Park', 'Nature', '3 hours', 120, 'Munnar'),
(7, 'Baga Beach', 'Nature', '3 hours', 0, 'Goa'),
(7, 'Basilica of Bom Jesus', 'Heritage', '1 hour', 0, 'Goa'),
(7, 'Dudhsagar Falls', 'Nature', '4 hours', 400, 'Goa'),
(7, 'Aguada Fort', 'Heritage', '2 hours', 0, 'Goa'),
(8, 'Taj Mahal', 'Heritage', '2.5 hours', 50, 'Agra'),
(8, 'Agra Fort', 'Heritage', '2 hours', 40, 'Agra'),
(8, 'Fatehpur Sikri', 'Heritage', '2.5 hours', 40, 'Agra'),
(8, 'Mehtab Bagh', 'Nature', '1 hour', 25, 'Agra'),
(9, 'Kashi Vishwanath Temple', 'Religious', '2 hours', 0, 'Varanasi'),
(9, 'Dashashwamedh Ghat', 'Religious', '2 hours', 0, 'Varanasi'),
(9, 'Sarnath', 'Heritage', '3 hours', 20, 'Varanasi'),
(9, 'Assi Ghat', 'Heritage', '1 hour', 0, 'Varanasi'),
(10, 'Laxman Jhula', 'Monument', '1 hour', 0, 'Rishikesh'),
(10, 'Triveni Ghat', 'Religious', '1.5 hours', 0, 'Rishikesh'),
(10, 'Beatles Ashram', 'Heritage', '2 hours', 150, 'Rishikesh'),
(10, 'Neelkanth Mahadev Temple', 'Religious', '2 hours', 0, 'Rishikesh'),
(11, 'Rohtang Pass', 'Nature', '4 hours', 500, 'Manali'),
(11, 'Hadimba Temple', 'Religious', '1 hour', 0, 'Manali'),
(11, 'Solang Valley', 'Nature', '3 hours', 0, 'Manali'),
(11, 'Old Manali', 'Heritage', '2 hours', 0, 'Manali'),
(12, 'The Ridge', 'Nature', '1 hour', 0, 'Shimla'),
(12, 'Mall Road', 'Market', '2 hours', 0, 'Shimla'),
(12, 'Jakhoo Temple', 'Religious', '1.5 hours', 0, 'Shimla'),
(12, 'Christ Church', 'Heritage', '1 hour', 0, 'Shimla'),
(13, 'Golden Temple', 'Religious', '3 hours', 0, 'Amritsar'),
(13, 'Jallianwala Bagh', 'Monument', '1.5 hours', 0, 'Amritsar'),
(13, 'Wagah Border', 'Monument', '3 hours', 0, 'Amritsar'),
(13, 'Partition Museum', 'Museum', '2 hours', 10, 'Amritsar'),
(14, 'City Palace', 'Heritage', '2.5 hours', 300, 'Udaipur'),
(14, 'Lake Pichola', 'Nature', '2 hours', 400, 'Udaipur'),
(14, 'Jag Mandir', 'Heritage', '1 hour', 0, 'Udaipur'),
(14, 'Saheliyon Ki Bari', 'Nature', '1 hour', 10, 'Udaipur'),
(15, 'Gateway of India', 'Monument', '1 hour', 0, 'Mumbai'),
(15, 'Marine Drive', 'Nature', '1.5 hours', 0, 'Mumbai'),
(15, 'Elephanta Caves', 'Heritage', '4 hours', 250, 'Mumbai'),
(15, 'Chhatrapati Shivaji Maharaj Terminus', 'Heritage', '1 hour', 0, 'Mumbai'),
(16, 'Lalbagh Botanical Garden', 'Nature', '2 hours', 20, 'Bengaluru'),
(16, 'Bangalore Palace', 'Heritage', '2 hours', 230, 'Bengaluru'),
(16, 'Cubbon Park', 'Nature', '2 hours', 0, 'Bengaluru'),
(16, 'Vidhana Soudha', 'Monument', '1 hour', 0, 'Bengaluru'),
(17, 'Charminar', 'Heritage', '1.5 hours', 25, 'Hyderabad'),
(17, 'Golconda Fort', 'Heritage', '3 hours', 25, 'Hyderabad'),
(17, 'Ramoji Film City', 'Entertainment', '6 hours', 1150, 'Hyderabad'),
(17, 'Hussain Sagar Lake', 'Nature', '1.5 hours', 0, 'Hyderabad'),
(18, 'Marina Beach', 'Nature', '2 hours', 0, 'Chennai'),
(18, 'Kapaleeshwarar Temple', 'Religious', '1.5 hours', 0, 'Chennai'),
(18, 'Fort St. George', 'Heritage', '2 hours', 15, 'Chennai'),
(18, 'San Thome Basilica', 'Religious', '1 hour', 0, 'Chennai'),
(19, 'Victoria Memorial', 'Heritage', '2.5 hours', 30, 'Kolkata'),
(19, 'Howrah Bridge', 'Monument', '1 hour', 0, 'Kolkata'),
(19, 'Dakshineswar Kali Temple', 'Religious', '2 hours', 0, 'Kolkata'),
(19, 'Indian Museum', 'Museum', '3 hours', 50, 'Kolkata'),
(20, 'Tiger Hill', 'Nature', '2.5 hours', 0, 'Darjeeling'),
(20, 'Batasia Loop', 'Monument', '1 hour', 20, 'Darjeeling'),
(20, 'Padmaja Naidu Himalayan Zoological Park', 'Nature', '2 hours', 60, 'Darjeeling'),
(20, 'Peace Pagoda', 'Religious', '1 hour', 0, 'Darjeeling'),
(21, 'Ooty Lake', 'Nature', '2 hours', 15, 'Ooty'),
(21, 'Botanical Gardens', 'Nature', '2 hours', 30, 'Ooty'),
(21, 'Doddabetta Peak', 'Nature', '1.5 hours', 10, 'Ooty'),
(21, 'Rose Garden', 'Nature', '1.5 hours', 20, 'Ooty'),
(22, 'Mysore Palace', 'Heritage', '2.5 hours', 70, 'Mysuru'),
(22, 'Chamundeshwari Temple', 'Religious', '2 hours', 0, 'Mysuru'),
(22, 'Brindavan Gardens', 'Nature', '2.5 hours', 15, 'Mysuru'),
(22, 'St. Philomena''s Cathedral', 'Religious', '1 hour', 0, 'Mysuru'),
(23, 'Cellular Jail', 'Heritage', '2.5 hours', 30, 'Andaman'),
(23, 'Radhanagar Beach', 'Nature', '3 hours', 0, 'Havelock Island'),
(23, 'Ross Island', 'Heritage', '2 hours', 30, 'Andaman'),
(23, 'Elephant Beach', 'Nature', '3 hours', 0, 'Havelock Island');


-- Foods
INSERT INTO foods (destination_id, name, category, price, dietary_type) VALUES
(1, 'Tunday Kababi', 'Non-Veg', 200, 'Non-Vegetarian'),
(1, 'Lucknowi Biryani', 'Non-Veg', 250, 'Non-Vegetarian'),
(1, 'Basket Chaat', 'Snack', 80, 'Vegetarian'),
(1, 'Kulcha Nihari', 'Non-Veg', 150, 'Non-Vegetarian'),
(1, 'Malai Makhan', 'Dessert', 50, 'Vegetarian'),
(2, 'Dal Baati Churma', 'Main Course', 150, 'Vegetarian'),
(2, 'Laal Maas', 'Main Course', 300, 'Non-Vegetarian'),
(2, 'Ghewar', 'Dessert', 100, 'Vegetarian'),
(2, 'Pyaaz Kachori', 'Snack', 40, 'Vegetarian'),
(3, 'Bal Mithai', 'Dessert', 100, 'Vegetarian'),
(3, 'Bhatt ki Churkani', 'Main Course', 120, 'Vegetarian'),
(3, 'Aloo ke Gutke', 'Snack', 60, 'Vegetarian'),
(3, 'Thukpa', 'Main Course', 90, 'Non-Vegetarian'),
(4, 'Momos', 'Snack', 80, 'Vegetarian'),
(4, 'Garhwali Thali', 'Main Course', 200, 'Vegetarian'),
(4, 'Bhutta', 'Snack', 40, 'Vegetarian'),
(4, 'Chola Bhatura', 'Main Course', 100, 'Vegetarian'),
(5, 'Chole Bhature', 'Main Course', 120, 'Vegetarian'),
(5, 'Butter Chicken', 'Main Course', 350, 'Non-Vegetarian'),
(5, 'Aloo Tikki', 'Snack', 60, 'Vegetarian'),
(5, 'Paranthe', 'Main Course', 90, 'Vegetarian'),
(6, 'Appam with Stew', 'Main Course', 120, 'Vegetarian'),
(6, 'Kerala Fish Curry', 'Main Course', 250, 'Non-Vegetarian'),
(6, 'Puttu and Kadala Curry', 'Main Course', 100, 'Vegetarian'),
(6, 'Banana Chips', 'Snack', 50, 'Vegetarian'),
(7, 'Goan Fish Curry', 'Main Course', 300, 'Non-Vegetarian'),
(7, 'Pork Vindaloo', 'Main Course', 350, 'Non-Vegetarian'),
(7, 'Bebinca', 'Dessert', 150, 'Vegetarian'),
(7, 'Prawn Balchão', 'Main Course', 400, 'Non-Vegetarian'),
(8, 'Petha', 'Dessert', 100, 'Vegetarian'),
(8, 'Bedmi Puri', 'Main Course', 80, 'Vegetarian'),
(8, 'Bhalla', 'Snack', 50, 'Vegetarian'),
(8, 'Mughlai Paratha', 'Main Course', 120, 'Non-Vegetarian'),
(9, 'Kachori Sabzi', 'Main Course', 50, 'Vegetarian'),
(9, 'Malaiyyo', 'Dessert', 80, 'Vegetarian'),
(9, 'Banarasi Paan', 'Snack', 30, 'Vegetarian'),
(9, 'Tamatar Chaat', 'Snack', 60, 'Vegetarian'),
(10, 'Aloo Poori', 'Main Course', 70, 'Vegetarian'),
(10, 'Chotiwala Thali', 'Main Course', 200, 'Vegetarian'),
(10, 'Masala Chai', 'Beverage', 20, 'Vegetarian'),
(10, 'Samosa', 'Snack', 20, 'Vegetarian'),
(11, 'Siddu', 'Main Course', 120, 'Vegetarian'),
(11, 'Trout Fish', 'Main Course', 400, 'Non-Vegetarian'),
(11, 'Chha Gosht', 'Main Course', 350, 'Non-Vegetarian'),
(11, 'Babru', 'Snack', 60, 'Vegetarian'),
(12, 'Madra', 'Main Course', 150, 'Vegetarian'),
(12, 'Dhaam', 'Main Course', 250, 'Vegetarian'),
(12, 'Tudkiya Bhath', 'Main Course', 100, 'Vegetarian'),
(12, 'Bhey', 'Snack', 80, 'Vegetarian'),
(13, 'Amritsari Kulcha', 'Main Course', 80, 'Vegetarian'),
(13, 'Lassi', 'Beverage', 50, 'Vegetarian'),
(13, 'Makki di Roti Sarson da Saag', 'Main Course', 150, 'Vegetarian'),
(13, 'Fish Tikka', 'Snack', 250, 'Non-Vegetarian'),
(14, 'Kachori', 'Snack', 40, 'Vegetarian'),
(14, 'Gatte ki Sabzi', 'Main Course', 180, 'Vegetarian'),
(14, 'Mirchi Bada', 'Snack', 30, 'Vegetarian'),
(14, 'Banjara Gosht', 'Main Course', 320, 'Non-Vegetarian'),
(15, 'Vada Pav', 'Snack', 30, 'Vegetarian'),
(15, 'Pav Bhaji', 'Main Course', 120, 'Vegetarian'),
(15, 'Bombay Sandwich', 'Snack', 60, 'Vegetarian'),
(15, 'Bhel Puri', 'Snack', 50, 'Vegetarian'),
(16, 'Bisi Bele Bath', 'Main Course', 100, 'Vegetarian'),
(16, 'Dosa', 'Main Course', 80, 'Vegetarian'),
(16, 'Filter Coffee', 'Beverage', 30, 'Vegetarian'),
(16, 'Chow Chow Bhath', 'Snack', 70, 'Vegetarian'),
(17, 'Hyderabadi Biryani', 'Main Course', 300, 'Non-Vegetarian'),
(17, 'Haleem', 'Main Course', 250, 'Non-Vegetarian'),
(17, 'Double ka Meetha', 'Dessert', 100, 'Vegetarian'),
(17, 'Irani Chai', 'Beverage', 25, 'Vegetarian'),
(18, 'Idli Sambhar', 'Main Course', 60, 'Vegetarian'),
(18, 'Chicken Chettinad', 'Main Course', 280, 'Non-Vegetarian'),
(18, 'Pongal', 'Main Course', 80, 'Vegetarian'),
(18, 'Mysore Pak', 'Dessert', 120, 'Vegetarian'),
(19, 'Rosogolla', 'Dessert', 30, 'Vegetarian'),
(19, 'Kathi Roll', 'Snack', 70, 'Non-Vegetarian'),
(19, 'Machher Jhol', 'Main Course', 200, 'Non-Vegetarian'),
(19, 'Phuchka', 'Snack', 30, 'Vegetarian'),
(20, 'Darjeeling Tea', 'Beverage', 50, 'Vegetarian'),
(20, 'Momos', 'Snack', 80, 'Non-Vegetarian'),
(20, 'Thukpa', 'Main Course', 100, 'Non-Vegetarian'),
(20, 'Churpee', 'Snack', 60, 'Vegetarian'),
(21, 'Ooty Chocolates', 'Dessert', 150, 'Vegetarian'),
(21, 'Avial', 'Main Course', 120, 'Vegetarian'),
(21, 'Neer Dosa', 'Main Course', 80, 'Vegetarian'),
(21, 'Chicken Curry', 'Main Course', 220, 'Non-Vegetarian'),
(22, 'Mysore Masala Dosa', 'Main Course', 90, 'Vegetarian'),
(22, 'Mysore Pak', 'Dessert', 100, 'Vegetarian'),
(22, 'Maddur Vada', 'Snack', 40, 'Vegetarian'),
(22, 'Bisi Bele Bath', 'Main Course', 100, 'Vegetarian'),
(23, 'Seafood Curry', 'Main Course', 350, 'Non-Vegetarian'),
(23, 'Grilled Lobster', 'Main Course', 800, 'Non-Vegetarian'),
(23, 'Fish Tikka', 'Snack', 300, 'Non-Vegetarian'),
(23, 'Coconut Water', 'Beverage', 50, 'Vegetarian');

-- Restaurants
INSERT INTO restaurants (destination_id, name, location, cuisine) VALUES
(1, 'Tunday Kababi', 'Aminabad, Lucknow', 'Awadhi'),
(1, 'Idris Biryani', 'Chowk, Lucknow', 'Mughlai'),
(1, 'Royal Cafe', 'Hazratganj, Lucknow', 'North Indian'),
(2, 'LMB (Laxmi Misthan Bhandar)', 'Johari Bazar, Jaipur', 'Rajasthani'),
(2, 'Rawat Mishtan Bhandar', 'Sindhi Camp, Jaipur', 'Snacks'),
(2, 'Handi Restaurant', 'MI Road, Jaipur', 'North Indian'),
(3, 'Machan Restaurant', 'Mall Road, Nainital', 'Multi-Cuisine'),
(3, 'Sakley''s Restaurant & Pastry Shop', 'Mall Road, Nainital', 'Continental'),
(3, 'Chandni Chowk', 'Mall Road, Nainital', 'North Indian'),
(4, 'Kalsang', 'Mall Road, Mussoorie', 'Tibetan'),
(4, 'Lovely Omelette Centre', 'Kulri Bazar, Mussoorie', 'Fast Food'),
(4, 'The Tavern', 'Picture Palace, Mussoorie', 'Multi-Cuisine'),
(5, 'Karim''s', 'Jama Masjid, Delhi', 'Mughlai'),
(5, 'Bukhara', 'ITC Maurya, Delhi', 'North Indian'),
(5, 'Indian Accent', 'The Lodhi, Delhi', 'Modern Indian'),
(6, 'Paragon', 'Kochi', 'Kerala'),
(6, 'Rapsy Restaurant', 'Munnar', 'Kerala'),
(6, 'Fort House Restaurant', 'Fort Kochi', 'Seafood'),
(7, 'Thalassa', 'Vagator, Goa', 'Greek'),
(7, 'Mum''s Kitchen', 'Panaji, Goa', 'Goan'),
(7, 'Gunpowder', 'Assagao, Goa', 'South Indian'),
(8, 'Pinch of Spice', 'Fatehabad Road, Agra', 'North Indian'),
(8, 'Joney''s Place', 'Taj Ganj, Agra', 'North Indian'),
(8, 'Esphahan', 'The Oberoi Amarvilas, Agra', 'Awadhi'),
(9, 'Kashi Chat Bhandar', 'Godowlia, Varanasi', 'Street Food'),
(9, 'Baati Chokha Restaurant', 'Teliyabag, Varanasi', 'North Indian'),
(9, 'Brown Bread Bakery', 'Bangali Tola, Varanasi', 'Continental'),
(10, 'Chotiwala', 'Swarg Ashram, Rishikesh', 'North Indian'),
(10, 'The Sitting Elephant', 'Haridwar Road, Rishikesh', 'Multi-Cuisine'),
(10, 'Beatles Cafe', 'Tapovan, Rishikesh', 'Healthy/Vegan'),
(11, 'Johnson''s Cafe', 'Circuit House Road, Manali', 'Continental'),
(11, 'Cafe 1947', 'Old Manali', 'Italian'),
(11, 'Chopsticks', 'Mall Road, Manali', 'Tibetan/Chinese'),
(12, 'Cafe Simla Times', 'Mall Road, Shimla', 'Multi-Cuisine'),
(12, 'Baljees', 'Mall Road, Shimla', 'North Indian'),
(12, 'Wake & Bake', 'Mall Road, Shimla', 'Continental'),
(13, 'Kesar Da Dhaba', 'Chowk Passian, Amritsar', 'Punjabi'),
(13, 'Bharawan Da Dhaba', 'Town Hall, Amritsar', 'Punjabi'),
(13, 'Makhan Fish & Chicken Corner', 'Majitha Road, Amritsar', 'North Indian'),
(14, 'Ambrai', 'Chand Pole, Udaipur', 'North Indian'),
(14, 'Upre', 'Pichola, Udaipur', 'Multi-Cuisine'),
(14, 'Natraj Dining Hall', 'City Center, Udaipur', 'Rajasthani Thali'),
(15, 'Trishna', 'Fort, Mumbai', 'Seafood'),
(15, 'Leopold Cafe', 'Colaba, Mumbai', 'Multi-Cuisine'),
(15, 'Bademiya', 'Colaba, Mumbai', 'Mughlai'),
(16, 'Vidyarthi Bhavan', 'Basavanagudi, Bengaluru', 'South Indian'),
(16, 'Toit', 'Indiranagar, Bengaluru', 'Pub/Brewery'),
(16, 'MTR (Mavalli Tiffin Room)', 'Lalbagh Road, Bengaluru', 'South Indian'),
(17, 'Paradise', 'Secunderabad, Hyderabad', 'Hyderabadi'),
(17, 'Bawarchi', 'RTC X Roads, Hyderabad', 'Hyderabadi'),
(17, 'Cafe Bahar', 'Basheerbagh, Hyderabad', 'Hyderabadi'),
(18, 'Murugan Idli Shop', 'T. Nagar, Chennai', 'South Indian'),
(18, 'Saravana Bhavan', 'Various locations, Chennai', 'South Indian'),
(18, 'Dakshin', 'Crowne Plaza, Chennai', 'South Indian'),
(19, 'Peter Cat', 'Park Street, Kolkata', 'Continental/Indian'),
(19, 'Flurys', 'Park Street, Kolkata', 'Bakery/Cafe'),
(19, 'Bhojohori Manna', 'Gariahat, Kolkata', 'Bengali'),
(20, 'Glenary''s', 'Nehru Road, Darjeeling', 'Bakery/Multi-Cuisine'),
(20, 'Keventer''s', 'Nehru Road, Darjeeling', 'English Breakfast'),
(20, 'Sonam''s Kitchen', 'Zakihussain Road, Darjeeling', 'Continental'),
(21, 'Earl''s Secret', 'Havelock Road, Ooty', 'Continental'),
(21, 'Shinkow''s', 'Commissioners Road, Ooty', 'Chinese'),
(21, 'Place to Bee', 'Club Road, Ooty', 'Italian'),
(22, 'Mylari', 'Nazarbad, Mysuru', 'South Indian'),
(22, 'RRR', 'Gandhi Square, Mysuru', 'Andhra'),
(22, 'Oyster Bay', 'Vijay Nagar, Mysuru', 'Multi-Cuisine'),
(23, 'Something Different', 'Havelock Island, Andaman', 'Multi-Cuisine'),
(23, 'Anju Coco Resto', 'Havelock Island, Andaman', 'Seafood'),
(23, 'Lighthouse Residency', 'Port Blair, Andaman', 'Seafood');

-- Souvenirs
INSERT INTO souvenirs (destination_id, name, price) VALUES
(1, 'Chikankari Kurta', 1500),
(1, 'Zardozi Work', 2000),
(1, 'Ittar (Perfume)', 500),
(2, 'Blue Pottery', 1000),
(2, 'Block Print Textiles', 1200),
(2, 'Mojari Shoes', 800),
(3, 'Pine Cone Crafts', 300),
(3, 'Aipan Art', 800),
(3, 'Fruit Jams', 200),
(4, 'Walking Sticks', 400),
(4, 'Tibetan Prayer Wheels', 600),
(4, 'Hand-knitted Shawls', 1500),
(5, 'Meenakari Jewelry', 2500),
(5, 'Spices from Khari Baoli', 500),
(5, 'Madhubani Paintings', 1500),
(6, 'Spices', 600),
(6, 'Coir Products', 400),
(6, 'Kathakali Masks', 800),
(7, 'Cashewnuts', 800),
(7, 'Feni', 600),
(7, 'Shell Crafts', 300),
(8, 'Miniature Taj Mahal', 500),
(8, 'Leather Goods', 1500),
(8, 'Petha', 300),
(9, 'Banarasi Silk Saree', 5000),
(9, 'Rudraksha Mala', 1000),
(9, 'Brassware', 1500),
(10, 'Yoga Mats/Clothes', 800),
(10, 'Ayurvedic Products', 600),
(10, 'Singing Bowls', 1500),
(11, 'Kullu Shawls', 2000),
(11, 'Dorjes', 500),
(11, 'Kesar (Saffron)', 1000),
(12, 'Himachali Caps', 400),
(12, 'Wooden Toys', 600),
(12, 'Kangra Tea', 800),
(13, 'Phulkari Dupatta', 1500),
(13, 'Punjabi Jutti', 800),
(13, 'Papad/Warian', 400),
(14, 'Miniature Paintings', 2500),
(14, 'Pichwai Art', 3000),
(14, 'Silver Jewelry', 4000),
(15, 'Dharavi Leather Goods', 2000),
(15, 'Gateway of India Souvenirs', 300),
(15, 'Bollywood Memorabilia', 1000),
(16, 'Mysore Silk Sarees', 6000),
(16, 'Sandalwood Products', 1500),
(16, 'Channapatna Toys', 800),
(17, 'Pearl Jewelry', 5000),
(17, 'Bidriware', 2500),
(17, 'Pochampally Sarees', 4000),
(18, 'Kanjeevaram Sarees', 8000),
(18, 'Bronze Idols', 3000),
(18, 'Filter Coffee Powder', 400),
(19, 'Terracotta Crafts', 800),
(19, 'Kantha Embroidery', 2000),
(19, 'Kalighat Paintings', 1500),
(20, 'Darjeeling Tea', 1000),
(20, 'Thangka Paintings', 3000),
(20, 'Woolen Garments', 1500),
(21, 'Homemade Chocolates', 600),
(21, 'Eucalyptus Oil', 300),
(21, 'Toda Embroidery', 1500),
(22, 'Sandalwood Soap/Oil', 800),
(22, 'Mysore Paintings', 2500),
(22, 'Silk Saree', 4000),
(23, 'Pearl Jewelry', 3000),
(23, 'Bamboo Crafts', 600),
(23, 'Coconut Shell Arts', 400);

-- Transport Options
INSERT INTO transport_options (from_destination, to_destination, destination_id, transport_type, provider, departure, arrival) VALUES
('Delhi', 'Lucknow', 1, 'Flight', 'IndiGo', '06:00', '07:05'),
('Delhi', 'Lucknow', 1, 'Train', 'Shatabdi Express', '06:10', '12:50'),
('Delhi', 'Lucknow', 1, 'Bus', 'UPSRTC Volvo', '22:00', '06:00'),
('Delhi', 'Jaipur', 2, 'Flight', 'Air India', '07:00', '08:00'),
('Delhi', 'Jaipur', 2, 'Train', 'Vande Bharat', '06:10', '10:20'),
('Delhi', 'Jaipur', 2, 'Bus', 'Zingbus', '08:00', '14:00'),
('Mumbai', 'Goa', 7, 'Flight', 'Akasa Air', '10:00', '11:15'),
('Mumbai', 'Goa', 7, 'Train', 'Tejas Express', '05:50', '14:20'),
('Mumbai', 'Goa', 7, 'Bus', 'IntrCity SmartBus', '20:00', '07:00'),
('Bengaluru', 'Mysuru', 22, 'Train', 'Vande Bharat', '10:20', '12:20'),
('Bengaluru', 'Mysuru', 22, 'Bus', 'KSRTC Airavat', '08:00', '11:30'),
('Bengaluru', 'Mysuru', 22, 'Cab', 'Uber Intercity', '09:00', '12:00'),
('Delhi', 'Agra', 8, 'Train', 'Gatimaan Express', '08:10', '09:50'),
('Delhi', 'Agra', 8, 'Bus', 'UPSRTC Volvo', '07:00', '11:00'),
('Delhi', 'Agra', 8, 'Cab', 'Ola Prime', '08:00', '11:30'),
('Kolkata', 'Darjeeling', 20, 'Flight', 'SpiceJet', '12:00', '13:10'),
('Kolkata', 'Darjeeling', 20, 'Train', 'Darjeeling Mail', '22:05', '08:00');
